packages:
  - fimidx-core
  - ixtb-nextjs
  - fimidx-node-server
  - fimidx-js
  - fimidx-mfdoc
  - fimidx-winston-transport
  - fimidx-console-like-logger
  - fimidx-log-files-consumer
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - sqlite3
  - unrs-resolver
